server:
  port: 9080
spring:
  application:
    name: movies-api
  data:
    mongodb:
      uri: mongodb://211.252.87.34:40008/moviesdb #mongodb://localhost:27017/moviesdb
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/company-services # http://localhost:8080/realms/company-services # http://211.252.87.34:40007/realms/company-services
jwt:
  auth:
    converter:
      resource-id: movies-app
      principal-attribute: preferred_username

app:
  cors:
    allowed-origins: http://localhost:3000
  keycloak:
    server : http://localhost:8080 # http://211.252.87.34:40007

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true

logging:
  level:
    org.springframework.security: DEBUG
    org:
      keycloak:
        admin:
          client: DEBUG
